baseurl = "https://oswalt.dev"
title = "Matt Oswalt"

theme = "anatole"

languagecode = "en"
googleAnalytics = "UA-23075631-1"

paginate = 20
canonifyurls = true

# pygmentsstyle = "b2"
# pygmentscodefences = true
# pygmentscodefencesguesssyntax = true

disqusShortname = ""

[permalinks]	
  post = "/:year/:month/:title/"

# Because I use HTML all over my blog posts
[markup.goldmark.renderer]
unsafe= true

[taxonomies]
# Plural seems to be required by anatole at least by default
tag = "tags"
category = "categories"
series = "series"  # From old blog stuff, when I did series on things. Keeping this around to just ensure it doesn't break

[params]
    author = "Matt Oswalt"
    description = "Perpetual Learner, Software Developer, Writer, and Public Speaker."
    keywords = "blog,developer,personal"
    info = "Perpetual Learner, Software Developer, Writer, and Public Speaker."

    displayMode = "dark"
    profilePicture = "avatar.jpg"
    footercontent = ""
    dateformat = "January 2, 2006"

    hideCredits = true
    hideCopyright = false

    rtl = false

    images = ["avatar.jpg"]
    title = "Matt Oswalt"

## Math settings
[params.math]
enable = false  # options: true, false. Enable math support globally, default: false. You can always enable math on per page.
use = "katex"  # options: "katex", "mathjax". default is "katex".

## Social links
# use 'fab' when brand icons, use 'fas' when standard solid icons.
[[params.socialIcons]]
icon = "fab fa-linkedin"
title = "Linkedin"
url = "https://www.linkedin.com/in/oswaltmatt/"

[[params.socialIcons]]
icon = "fab fa-github"
title = "GitHub"
url = "https://github.com/mierdin/"

[[params.socialIcons]]
icon = "fab fa-twitter"
title = "twitter"
url = "https://twitter.com/mierdin/"

[[params.socialIcons]]
icon = "fa fa-rss"
title = "RSS"
url = "/feed.xml"

[[params.socialIcons]]
icon = "fab fa-facebook"
title = "Facebook"
url = "https://www.facebook.com/keepingitclassless/"

[[params.socialIcons]]
icon = "fab fa-youtube"
title = "YouTube"
url = "https://www.youtube.com/user/keepingitclassless"

[languages]
    [languages.en]
        languagename = "English"
        title = "Matt Oswalt"

        [languages.en.params]
        author = "Matt Oswalt"
        keywords = "blog,developer,personal"

        [languages.en.menu]

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1
        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Programming"
        weight = 3
        url = "/categories/programming/"

        [[languages.en.menu.main]]
        name = "Infrastructure"
        weight = 4
        url = "/categories/infrastructure/"

        # TODO - enable when you have graphics posts
        #[[languages.en.menu.main]]
        #name = "Graphics"
        #weight = 5
        #url = "/categories/graphics/"

        [[languages.en.menu.main]]
        name = "Bookshelf"
        weight = 6
        url = "/bookshelf/"

        [[languages.en.menu.main]]
        name = "Portfolio"
        weight = 7
        url = "/portfolio/"

[outputs]
home = ["HTML", "AMP", "RSS"]
page = ["HTML"]

[outputFormats]
[outputFormats.HTML]
mediaType = "text/html"

[outputFormats.RSS]
mediatype = "application/rss"
baseName = "feed"   # results in /feed.xml

