baseurl = "https://oswalt.dev"
title = "Matt Oswalt"

theme = "hugo-coder"

languagecode = "en"
googleAnalytics = "UA-23075631-1"

paginate = 20
canonifyurls = true

pygmentsstyle = "b2"
pygmentscodefences = true
pygmentscodefencesguesssyntax = true

disqusShortname = ""

[permalinks]
  post = "/:year/:month/:title/"

# Because I use HTML all over my blog posts
[markup.goldmark.renderer]
unsafe= true

[params]
    author = "Matt Oswalt"
    description = "Perpetual Learner, Software Developer, Writer, and Public Speaker."
    keywords = "programming,networks,automation,infrastructure,rust,golang"
    info = "Perpetual Learner, Software Developer, Writer, and Public Speaker."

    avatarurl = "avatar.jpg"
    footercontent = ""
    dateformat = "January 2, 2006"

    # Custom CSS
    custom_css = ["/css/custom.css"]

    images = ["avatar.jpg"]
    title = "Matt Oswalt"

    hideFooter = false
    hideCredits = true
    hideCopyright = false
    since = 2010

    # Git Commit in Footer, uncomment the line below to enable it.
    commit = "https://github.com/luizdepra/hugo-coder/tree/"

    rtl = false

    # Specify light/dark colorscheme
    # Supported values:
    # "auto" (use preference set by browser)
    # "dark" (dark background, light foreground)
    # "light" (light background, dark foreground) (default)
    colorScheme = "dark"

    # Hide the toggle button, along with the associated vertical divider
    hideColorSchemeToggle = false

    # Series see also post count
    maxSeeAlsoItems = 5

    # Enable Twemoji
    enableTwemoji = false

    # Custom CSS
    customCSS = []

    # Custom SCSS
    customSCSS = []

    # Custom JS
    customJS = []

# If you want to use Cloudflare Web Analytics(https://cloudflare.com) for analytics, add this section
[params.cloudflare]
    token = "token"

[taxonomies]
# Plural seems to be required by anatole at least by default
tag = "tags"
category = "categories"
series = "series"  # From old blog stuff, when I did series on things. Keeping this around to just ensure it doesn't break

[[params.social]]
    name = "Github"
    icon = "fa fa-github"
    weight = 1
    url = "https://github.com/mierdin/"
[[params.social]]
    name = "Twitter"
    icon = "fa fa-twitter"
    weight = 2
    url = "https://twitter.com/mierdin/"
[[params.social]]
    name = "LinkedIn"
    icon = "fa fa-linkedin"
    weight = 3
    url = "https://www.linkedin.com/in/oswaltmatt/"
[[params.social]]
    name = "YouTube"
    icon = "fa fa-youtube"
    weight = 4
    url = "https://www.youtube.com/user/keepingitclassless"
[[params.social]]
    name = "Facebook"
    icon = "fa fa-facebook"
    weight = 5
    url = "https://www.facebook.com/moswalt/"
[[params.social]]
    name = "RSS"
    icon = "fa fa-rss"
    weight = 6
    url = "/feed/"
    rel = "alternate"
    type = "application/rss+xml"

[params.utterances]
  repo = "Mierdin/blog" # https://utteranc.es/#heading-repository
  issueTerm = "pathname" # https://utteranc.es/#heading-mapping
  label = "comment" # https://utteranc.es/#heading-issue-label
  theme = "github-light" # https://utteranc.es/#heading-theme

[languages]
    [languages.en]
        languagename = "English"
        title = "Matt Oswalt"

        [languages.en.params]
        author = "Matt Oswalt"
        keywords = "programming,networks,automation,infrastructure,rust,golang"

        [languages.en.menu]

        [[languages.en.menu.main]]
        name = "Home"
        weight = 1
        url = "/"

        [[languages.en.menu.main]]
        name = "About"
        weight = 2
        url = "/about/"

        [[languages.en.menu.main]]
        name = "Programming"
        weight = 3
        url = "/categories/programming/"

        [[languages.en.menu.main]]
        name = "Infrastructure"
        weight = 4
        url = "/categories/infrastructure/"

        [[languages.en.menu.main]]
        name = "Personal"
        weight = 5
        url = "/categories/personal/"

        # TODO - enable when you have graphics posts
        #[[languages.en.menu.main]]
        #name = "Graphics"
        #weight = 6
        #url = "/categories/graphics/"

        [[languages.en.menu.main]]
        name = "Bookshelf"
        weight = 7
        url = "/bookshelf/"

