[context.production.environment]
  HUGO_VERSION = "0.78.2"

[context.deploy-preview.environment]
  HUGO_VERSION = "0.78.2"

# hugo extended required by new hugo-coder theme
# Netlify doesn't seem to run this right now so I'm running it locally, and if any changes are made to the resources/ directory,
# I'm committing them. This should be figured out soon, netlify should be able to do everything on its own too
# (Actually it works even if I don't commit these. So maybe I should add these to gitignore?)
[context.deploy-preview]
  command = "hugo --buildDrafts --buildFuture"

[[redirects]]
  from = "/feed"
  to = "/feed.xml"